### ISSUE TITLE
Can you please update the read.me file with the dataset pattern?

### ISSUE THREAD

**Issue by JafferWilson** [inikdom/neural-chatbot#16]
Hello,
I would like to know the pattern in which I need to provide the dataset to the program. If possible please add some test datasets, so that the idea will be clear.

**Comment by inikdom** [comment]
I've update the readme, I hope it's a bit clearer. I think it would be best if I prepared a sample dataset. I have a few, I'll dig through my datasets to find one. 

The main problem with this project right now is that it was made with an earlier tensorflow version. I need to update it to work with the latest tensorflow. That might take a while, as I anticipate redoing large portions of it (tensorboard and the rnn api calls have changed a fair amount). 

I'm leaving this issue open until I add the sample dataset

**Comment by JafferWilson** [comment]
@inikdom Thank you for your reply. I am eagerly waiting for your next update... :)

**Comment by domerin0** [comment]
I've added the dataset. I also updated the project for TF 1.2. I'm going to close this issue because the dataset is now available to go (data/cornell_lines). Feel free to open another issue if you have questions or run into any problems. 

Warning, I have not yet testing sampling after training, but I will be working on that over the next few days.
